### ISSUE TITLE
ApplyButtonLayout Enhancement

### ISSUE THREAD

**Issue by srd-software** [Alexey-T/ATTabs#44]
Just an idea Alexey. Would it be possible to add 2 chars to the OptButtonLayout set of possible chars? Like:

#32 (space)
| (pipe)

- Space: I would see this as a non-functional (no highlight, no hint, no click event needed), fixed-width "blank" OptButton that would let the designer insert a space in front of or behind any of the other functional OptButtons.

- | Pipe: Again, non-functional, fixed width and would tell the component to draw a separator (like a flat separator) which you could insert in front of or behind the other functional OptButtons.

Stan

**Comment by Alexey-T** [comment]
Good idea, maybe soon will try it.

**Comment by srd-software** [comment]
Thanks Alexey.

Here are some examples (these are just manipulated screenshots) to show how I see the effect of various OptButtonLayout (I'll show spaces as underscores in the text below). See the top tabset for the ideas; disregard the lower tabset:

"01<>,v" (default usage):

![original](https://user-images.githubusercontent.com/51385541/59347706-88f09600-8cd2-11e9-92d8-f4198c215b1f.png)

"_01<>,v" (leading space):

![leftspace](https://user-images.githubusercontent.com/51385541/59347833-db31b700-8cd2-11e9-8fd4-2259f46f798a.png)

"_0|1<>,v" (leading space and pipe):

![leadingspace_pipe](https://user-images.githubusercontent.com/51385541/59347916-0916fb80-8cd3-11e9-941c-7ee61389e38f.png)

"&lowbar;01|&lowbar;<>,v" (leading space, trailing pipe, trailing space):

![leadingspace_pipe_space](https://user-images.githubusercontent.com/51385541/59347954-1b913500-8cd3-11e9-9a5c-36299bd5d401.png)

**Comment by srd-software** [comment]
BTW, low priority for when you have some time. I can also give this a shot if you prefer, just let me know.

**Comment by Alexey-T** [comment]
Pls try to do it

**Comment by srd-software** [comment]
OK, will look at it in the morning. We were in Santa Fe today just to relax. Went up and back on the train which was fun too.

**Comment by srd-software** [comment]
Alexey, I'll make a pull request for all this and try to reference it here. Take your time to review if you are busy, low priority...

This is the best I could come up with to add user separators. As far as I could see, I only had 2 ways to go: deal with the various rectangles (i.e., in GetRectOfButtonIndex) or drawing. I could never get the rectangles to work with various sizes (Result.Left always has to be AIndex*FOptButtonSize and you can't mix rect widths as far as I could tell).

So I went with drawing instead and created a new public proc: **DrawUserButton**. Please take a look. This may not fit with what you want to do and that's OK, I can still do everything shown here in my app but this is more convenient to use plus it might make things easier for new users of the tabs. If you don't want to implement that's OK too!

User would probably call **DrawUserButton** from OnTabDrawAfter (that's where I'm calling it from). Here's how I have it in my test app and it works well:
```
//TabID can be cTabIndexUser0, #cTabIndexUser1, etc.
//Draw a highlight background: 
if (AElemType = aeButtonUser) or (AElemType = aeButtonUserOver) then
  aTabSet.DrawUserButton(ACanvas,TabID,ImgID,sepNone,$000066CA);

//Draw image:
aTabSet.DrawUserButton(ACanvas,TabID,ImgID);

//Draw image and add a separator to the right side of   ##tab:
aTabSet.DrawUserButton(ACanvas,TabID,ImgID,sepRight);
```
Also, I wanted an initial space before the first userbutton and the only way I could figure out to do it was to change +1 to OptSpaceInitial (below). May be a better way or need additional var/property for this?
```
function TATTabs.GetRectOfButtonIndex(AIndex: integer; AtLeft: boolean): TRect;
begin
  if AtLeft then
  begin
    Result.Left:= AIndex*FOptButtonSize
      +IfThen(FOptPosition=atpLeft, FOptSpacer)
      +IfThen(FOptPosition=atpRight, FOptSpacer2)
      +OptSpaceInitial; //changed from 1 to OptSpaceInitial <<<<<<<<<<<<<<<<<
    Result.Right:= Result.Left + FOptButtonSize;
...
```
Final result (initial space, 2 userbuttons and separator on right side of 2nd user button):

![Image15](https://user-images.githubusercontent.com/51385541/59470000-aec18c00-8df3-11e9-913a-b894854bd3bf.png)
#

**Comment by Alexey-T** [comment]
Commented the patch.

Also pls check this- set OptSpaceInitial to eg 15 and all must be correct.

**Comment by Alexey-T** [comment]
Note.
Need separator kind "centered vertical" and "centered horizontal".

**Comment by Alexey-T** [comment]
Now I see it must be made in other way, so sorry, I decline patch and write my own code

**Comment by srd-software** [comment]
No problem, I was afraid that might be the case!

**Comment by Alexey-T** [comment]
Try the code. i tested demo layout like this

    ||2_0||1,|<>|+x_4|

**Comment by Alexey-T** [comment]
Size of | and _ buttons are new properties- OptButtonSizeSpace, OptButtonSizeSeparator

**Comment by srd-software** [comment]
Yes, all that seems to work! I'm amazed. Thanks. I actually started down that path originally, but I could see early on that it was a bigger change to your code than I wanted to do or would be able to do. I got the initial vars and a few other pieces in there just like you used, but there are now some added functions and changes to others I would never have been able to pull off! Thanks Alexey. You are amazingly good at this stuff.

**Comment by srd-software** [comment]
I did find one issue. When I place a new default tabset on the form I get this:

![Image16](https://user-images.githubusercontent.com/51385541/59515658-d7419880-8e7c-11e9-90c4-5f2a972e73dc.png)

I have to add a leading space or pipe now to get it to set correctly. If I then remove the leading space or pipe, it then looks OK in the IDE but looks like the image above in runtime. Might have something to do with the FRealIndentLeft/Right vars but I'm not sure. I fiddled with it a little and couldn't get it fixed.

**Comment by srd-software** [comment]
OK, moving ApplyButtonLayout; from line 1153 (in my IDE) to the end of the create constructor seems to fix this.

**Comment by Alexey-T** [comment]
Fixed it hour ago

**Comment by srd-software** [comment]
Is it in the regular code download now? I tried that one and it's still not working here. Also missing the public TabMenu: TATTabPopupMenu; to assign a user tab menu? Or was that part of the issue?

**Comment by Alexey-T** [comment]
TabMenu renamed to TabMenuExternal. it is in the latest Github version.

**Comment by Alexey-T** [comment]
Still see that paint error? i need a demo to see it? or just place empty Tabs on a form?

**Comment by srd-software** [comment]
Yes, still getting the paint problem. Just put a new tabset on the form and you get:

![Image17](https://user-images.githubusercontent.com/51385541/59521289-360d0f00-8e89-11e9-9b2d-825ea552e3e9.png)

There should be <> at left and v on right as the OptButtonLayout is correct: <>,v

Also, if there's an existing tabset with just the default layout (<>,v), it does not show correctly either:

![Image19](https://user-images.githubusercontent.com/51385541/59521496-a025b400-8e89-11e9-88b3-37005c1ddf68.png)

If the tabset has some extra stuff in it, i.e., "0|1<>,v" then it displays OK.

If I move the ApplyButtonLayout call in the create constructor it seems to fix it. I think it's being called too soon in the constructor, but not sure moving it is the best fix.

**Comment by Alexey-T** [comment]
You are right, fixed, try again

**Comment by srd-software** [comment]
Yes, looks OK now, thanks.
